### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by Vict0r-M** [jhc13/2x2-cube-solver#1]
Hello, I tried to run train.py with default values and I had the following error:

```
(varikon) viktor@zamolxe:~/projects/2x2-cube-solver/2x2-cube-solver$ export CUDA_VISIBLE_DEVICES="0,1"
(varikon) viktor@zamolxe:~/projects/2x2-cube-solver/2x2-cube-solver$ python train.py
Using device: cuda.
Traceback (most recent call last):
  File "/home/viktor/projects/2x2-cube-solver/2x2-cube-solver/train.py", line 319, in <module>
    trainer = Trainer(seed=13)
  File "/home/viktor/projects/2x2-cube-solver/2x2-cube-solver/train.py", line 28, in __init__
    self.env = CubeEnv()
  File "/home/viktor/projects/2x2-cube-solver/2x2-cube-solver/cube_env.py", line 19, in __init__
    'action_mask': spaces.Box(low=False, high=True, shape=(6,),
  File "/home/viktor/anaconda3/envs/varikon/lib/python3.9/site-packages/gym/spaces/box.py", line 109, in __init__
    low = _broadcast(low, dtype, shape, inf_sign="-")  # type: ignore
  File "/home/viktor/anaconda3/envs/varikon/lib/python3.9/site-packages/gym/spaces/box.py", line 332, in _broadcast
    assert isinstance(value, np.ndarray)
AssertionError
```

Any advice? Thank you.

**Comment by jhc13** [comment]
Hello, did you install the exact versions of the packages specified in `requirements.txt`?

**Comment by Vict0r-M** [comment]
After installing the exact versions, it worked, thank you.
